feat : 랭킹 정보 조회 api 추가
alstn2468/maplestory-open-api-js pull request #2
Opened 2023-12-30 11:37 UTC by HA-SEUNG-JEONG

OverallRanking, UnionRanking, GuildRanking, DojangRanking, TheSeedRanking, ErrorMessage 인터페이스 추가

2023-12-30 12:57 UTC, alstn2468 reviewed
에러메세지만 제거해주시고 상세한거는 더 확인하구 머지하겠습니다!
PR이름에 api 타입 추가라고 적어주시면 더 좋을 것 같아요!

2023-12-30 12:57 UTC, alstn2468 commented on packages/maplestory-open-api-js/src/types/ranking.ts
> +export interface ErrorMessage extends RankingBase {
에러는 따로 빼두어서 없어도 괜찮을 것 같아요

2023-12-30 13:17 UTC, HA-SEUNG-JEONG commented on packages/maplestory-open-api-js/src/types/ranking.ts
> +export interface ErrorMessage extends RankingBase {
수정했습니다!

2023-12-31 12:17 UTC, alstn2468 requested changes

2023-12-31 12:17 UTC, alstn2468 commented on packages/maplestory-open-api-js/src/types/ranking.ts
> +  ranking: CommonRankingProps & {
<img width="287" alt="image" src="https://github.com/alstn2468/maplestory-open-api-js/assets/30997311/4732eb74-23e4-41b6-8563-54e599743719">

실제 응답값이 배열 형태로 보여집니다. 반영이 필요할 듯 합니다.
date 또한 배열 내부 요소에 있는 것으로 보여서 구조 자체가 수정되어야할 듯 합니다.
다른 `ranking` 필드들도 동일한 것 같아요. 실제 응답 예시랑 비교해보시는 것이 좋을 것 같습니다.

2024-01-01 13:48 UTC, alstn2468 requested changes

2024-01-01 13:48 UTC, alstn2468 commented on packages/maplestory-open-api-js/src/types/ranking.ts
> +    }[];
`&` 이 정상적으로 사용되지 않고있습니다!

- 괄호로 우선순위 이용

```suggestion
  ranking: (CommonRankingProps &
    {
      /** 캐릭터 레벨 */
      character_level: number;
      /** 캐릭터 경험치 */
      character_exp: number;
      /** 캐릭터 인기도 */
      character_popularity: number;
      /** 길드 명 */
      character_guildname: string;
    })[];
```

- 제네릭 이용

```suggestion
  ranking: Array<CommonRankingProps &
    {
      /** 캐릭터 레벨 */
      character_level: number;
      /** 캐릭터 경험치 */
      character_exp: number;
      /** 캐릭터 인기도 */
      character_popularity: number;
      /** 길드 명 */
      character_guildname: string;
    }>;
```

2024-01-01 13:48 UTC, alstn2468 commented on packages/maplestory-open-api-js/src/types/ranking.ts
> +}
```suggestion
export interface CommonRankingProps<T extends Record<string, unkown>> {
  /** 랭킹 업데이트 일자 (KST, 일 단위 데이터로 시, 분은 일괄 0으로 표기)
   * example: 2023-12-21T00:00+09:00
   * */
  date: string;
  /** 종합 랭킹 순위 */
  ranking: number;
  /** 캐릭터 명 */
  character_name: string;
  /** 월드 명 */
  world_name: string;
  /** 직업 명 */
  class_name: string;
  /** 전직 직업 명 */
  sub_class_name: string;
} & T
```

느낌으로도 작성할 수 있을 것 같네요~!

2024-01-01 14:28 UTC, HA-SEUNG-JEONG commented on packages/maplestory-open-api-js/src/types/ranking.ts
> +    }[];
반영했습니다!

2024-01-01 15:26 UTC, alstn2468 approved these changes

2024-01-01 15:27 UTC, merged